@startuml

skinparam monochrome true

[ATraceImpl]

() "ATrace"

[ATraceImpl] - ATrace

[CmdLineApp] ..> ATrace: uses 

[ATraceImpl] ..> FTrace: uses
[ATraceImpl] ..> Android: uses

[ATraceImplTest] ..> ATrace: uses

[MockFTrace] - FTrace
[MockAndroid] - Android

@enduml