@startuml

class CmdLineApp {
  + run(): int
  + handleSignal(): void
}
hide CmdLineApp fields

CmdLineApp "m_Wire" -- "1" Wire
CmdLineApp "m_CmdLineArgs" -- "1" CmdLineArgs
CmdLineApp "m_ActionCmdLineBuilder" -- "1" ActionCmdLineBuilder
CmdLineApp "m_Signal" -- "1" Signal

class Wire {
  - m_ErrorStream: FILE *
  - m_OutputStream: FILE *
  --
  + getErrorStream(): FILE *
  + getOutputStream(): FILE *
}
hide Wire methods

class Signal {
  - isFired: bool
  --
  + fire(): void
  + isFired(): bool
}

class CmdLineArgs {
  - m_AppName: string
  - m_Args: vector<string>
  --
  + getCount(): int
  + get(id: int): string
  + getAppName(): string  
}

interface ActionCmdLineBuilder {
  + {abstract} build(wire: Wire, signal: Signal, cmdLineArgs: CmdLineArgs): Action
}
hide ActionCmdLineBuilder fields

class TraceActionsRunnerCmdLineBuilder {
  + build(wire: Wire, signal: Signal, cmdLineArgs: CmdLineArgs): Action 
}
hide TraceActionsRunnerCmdLineBuilder fields

TraceActionsRunnerCmdLineBuilder .> ActionCmdLineBuilder
TraceActionsRunnerCmdLineBuilder "-m_TraceArgumentsBuilder" -- "1" TraceArgumentsBuilder
TraceActionsRunnerCmdLineBuilder "-m_TraceSystemBuilder" -- "1" TraceSystemBuilder
TraceActionsRunnerCmdLineBuilder "-m_TraceActionsRunnerBuilder" -- "1" TraceActionsRunnerBuilder
TraceActionsRunnerCmdLineBuilder --> Environment: uses

class TraceArgumentsBuilder {
  + build(wire: Wire, cmdLineArgs: CmdLineArgs): TraceArguments
  - createHelpTraceArguments(): TraceArguments
  - createTraceArguments(arguments: Arguments): TraceArguments
  - getHelpMessage(): string
}
hide TraceArgumentsBuilder fields

class TraceSystemBuilder {
  + build(wire: Wire, traceArguments: TraceArguments): TraceSystem
}
hide TraceSystemBuilder fields

class TraceActionsRunnerBuilder {
  + build(wire: Wire, environment: Environment, traceSystem: TraceSystem, traceArgs: TraceArguments): TraceActionsRunner
}
hide TraceActionsRunnerBuilder fields

class Environment {
  - m_Name: string
  - m_CanBeInterrupted: bool
  --
  + isInterrupted(): bool
}

Environment "-m_Signal" -- "1" Signal


@enduml