@startuml

class CmdLineApp {
  - m_AppName: string
  --
  + run(): int
  + handleSignal(): void
}

CmdLineApp "m_Wire" -- "1" Wire
CmdLineApp "m_CmdLineArgs" -- "1" CmdLineArgs
CmdLineApp "m_ActionCmdLineBuilder" -- "1" ActionCmdLineBuilder
CmdLineApp "m_Signal" -- "1" Signal

class Wire {
  - m_ErrorStream: FILE *
  - m_OutputStream: FILE *
  --
  + getErrorStream(): FILE *
  + getOutputStream(): FILE *
}
hide Wire methods

class Signal {
  - isFired: bool
  --
  + fire(): void
  + isFired(): bool
}

class CmdLineArgs {
  - m_Args: vector<string>
  --
  + getCount(): int
  + get(id: int): string  
}

interface ActionCmdLineBuilder {
  + build(wire: Wire, signal: Signal, appName: string, cmdLineArgs: CmdLineArgs): Action
}
hide ActionCmdLineBuilder fields

@enduml