@startuml

title Class Diagram

class TraceApp {
  + tryAct(): bool
}
hide TraceApp fields

TraceApp *--> "1" TraceAction

interface TraceAction {
  + {abstract} tryExecute(): bool
}
hide TraceAction fields

class DumpTraceAction {
  - tryDumpBuffer(): bool
}
hide DumpTraceAction fields

DumpTraceAction ..> TraceAction
DumpTraceAction "-traceBuffer" --> "1" TraceBuffer

class StartTraceAction {
  - tryStartSession(): bool
}
hide StartTraceAction fields

StartTraceAction ..> TraceAction

class StopTraceAction {
  - tryStopSession(): bool
}
hide StopTraceAction fields

StopTraceAction ..> TraceAction



@enduml