@startuml

title Domain Model

class KernelTraceCategory {
}
hide KernelTraceCategory circle
hide KernelTraceCategory methods
hide KernelTraceCategory fields

KernelTraceCategory --|> KernelTraceable
KernelTraceCategory "1" -- "1..*" KernelTraceCategoryFeature: requires >

class AndroidTraceCategory {
  - tag_id: int
}
hide AndroidTraceCategory circle
hide AndroidTraceCategory methods

AndroidTraceCategory --|> AndroidTraceable

class KernelTraceFile {
  - path: string
}
hide KernelTraceFile circle
hide KernelTraceFile methods

class EnableFile {
  ' indicates if file enables smth
  - is_enabled: bool
}
hide EnableFile circle
hide EnableFile methods

class KernelTraceCategoryFeature {
}
hide KernelTraceCategoryFeature circle
hide KernelTraceCategoryFeature methods
hide KernelTraceCategoryFeature fields

EnableFile --|> KernelTraceFile
EnableFile "1" -- "1" KernelTraceCategoryFeature: enables >
EnableFile "1" - "1" Trace: enables >

class Trace {
}
hide Trace circle
hide Trace methods
hide Trace fields

Trace -- TraceComponent: starts

class KernelTrace {
}
hide KernelTrace circle
hide KernelTrace methods
hide KernelTrace fields

KernelTrace --|> TraceComponent
KernelTrace "1" -- "1..*" KernelTraceFile: has >
KernelTrace "1" -- "1..*" KernelTraceable: traces >
KernelTrace "1" -- "1..*" KernelTraceable: supports >

class FunctionTraceFile {
}
hide FunctionTraceFile circle
hide FunctionTraceFile methods
hide FunctionTraceFile fields

FunctionTraceFile --|> KernelTraceFile
FunctionTraceFile -- KernelFunction: specifies >

class KernelTraceable {
  - name: string
}
hide KernelTraceable circle
hide KernelTraceable methods

class AndroidTrace {
}
hide AndroidTrace circle
hide AndroidTrace methods
hide AndroidTrace fields

AndroidTrace --|> TraceComponent
AndroidTrace "1" -- "1..*" AndroidTraceable: traces >

class AndroidSystem {
}
hide AndroidSystem circle
hide AndroidSystem methods
hide AndroidSystem fields

AndroidSystem "1" -- "1..*" AndroidProperty: reads >
AndroidSystem "1" -- "1..*" AndroidProperty: writes >

class TraceComponent {
}
hide TraceComponent methods
hide TraceComponent fields
hide TraceComponent circle

' this is done transparently
TraceComponent "1" -- "1" TraceBuffer: logs into >

class KernelFunction {
}
hide KernelFunction circle
hide KernelFunction methods
hide KernelFunction fields

KernelFunction --|> KernelTraceable

class AndroidTraceable {
  - name : string
}
hide AndroidTraceable circle
hide AndroidTraceable methods

class AndroidApp {
}
hide AndroidApp circle
hide AndroidApp methods
hide AndroidApp fields

AndroidApp --|> AndroidTraceable

class AndroidCoreService {
}
hide AndroidCoreService circle
hide AndroidCoreService methods
hide AndroidCoreService fields

AndroidCoreService --|> AndroidApp

class AndroidProperty {
  - name : string
}
hide AndroidProperty circle
hide AndroidProperty methods

class AndroidCoreServiceProperty {
}
hide AndroidCoreServiceProperty circle
hide AndroidCoreServiceProperty methods

AndroidCoreServiceProperty --|> AndroidProperty
AndroidCoreServiceProperty "1" -- "1" AndroidCoreService: stores

class AndroidTraceCategoriesProperty {
}
hide AndroidTraceCategoriesProperty circle
hide AndroidTraceCategoriesProperty methods
hide AndroidTraceCategoriesProperty fields

AndroidTraceCategoriesProperty --|> AndroidProperty
AndroidTraceCategoriesProperty "1" -- "1..*" AndroidTraceCategory: stores

class AndroidTraceAppsProperty {
}
hide AndroidTraceAppsProperty circle
hide AndroidTraceAppsProperty methods
hide AndroidTraceAppsProperty fields

AndroidTraceAppsProperty --|> AndroidProperty
AndroidTraceAppsProperty -- "1..16" AndroidApp: stores

class AndroidTraceAppCounterProperty {
  - count: int
}
hide AndroidTraceAppCounterProperty circle
hide AndroidTraceAppCounterProperty methods

AndroidTraceAppCounterProperty --|> AndroidProperty
AndroidTraceAppCounterProperty -- AndroidApp: counts

class TraceBuffer {
  - size: int
}
hide TraceBuffer circle
hide TraceBuffer methods

TraceBuffer "1..*" -- "1" BufferMode: is in >
TraceBuffer --|> KernelTraceFile

class BufferMode {
}
hide BufferMode circle
hide BufferMode methods
hide BufferMode fields

class CircularBufferMode {
}
hide CircularBufferMode circle
hide CircularBufferMode methods
hide CircularBufferMode fields

CircularBufferMode --|> BufferMode

class WriteUntilFullBufferMode {
}
hide WriteUntilFullBufferMode circle
hide WriteUntilFullBufferMode methods
hide WriteUntilFullBufferMode fields

WriteUntilFullBufferMode --|> BufferMode

class TraceApp {
}
hide TraceApp circle
hide TraceApp methods
hide TraceApp fields

TraceApp "1" -- "1" TraceSession: starts >

class TraceSession {
  - delay_at_start: int
}
hide TraceSession circle
hide TraceSession methods

TraceSession "1" - "1..*" KernelTraceable: traces >
TraceSession "1" - "1..*" AndroidTraceable: traces >

class AsyncTraceSession {
}
hide AsyncTraceSession circle
hide AsyncTraceSession methods
hide AsyncTraceSession fields

AsyncTraceSession --|> TraceSession
AsyncTraceSession "1" -- "1" TraceAction: does >

class SyncTraceSession {
  - duration: int
  - ignores_os_signals: bool
}
hide SyncTraceSession circle
hide SyncTraceSession methods

SyncTraceSession --|> TraceSession
SyncTraceSession "1" -- "1" StartTrace: does >
SyncTraceSession "1" -- "1" StopTrace: does >
SyncTraceSession "1" -- "1" DumpTrace: does >

class StreamTraceSession {
}
hide StreamTraceSession circle
hide StreamTraceSession fields
hide StreamTraceSession methods

StreamTraceSession --|> TraceSession
StreamTraceSession "1" -- "1" StartTrace: does >
StreamTraceSession "1" -- "1" StopTrace: does >
StreamTraceSession "1" -- "1" StreamTrace: does >

class TraceAction {
}
hide TraceAction circle
hide TraceAction methods
hide TraceAction fields

class StartTrace {
}
hide StartTrace circle
hide StartTrace methods
hide StartTrace fields

StartTrace --|> TraceAction
StartTrace -- Trace: starts >

class StopTrace {
}
hide StopTrace circle
hide StopTrace methods
hide StopTrace fields

StopTrace --|> TraceAction
StopTrace -- Trace: stops >

class StreamTrace {
}
hide StreamTrace circle
hide StreamTrace methods
hide StreamTrace fields

StreamTrace --|> TraceAction
StreamTrace -- Trace: streams >

class DumpTrace {
}
hide DumpTrace circle
hide DumpTrace methods
hide DumpTrace fields

DumpTrace --|> TraceAction
DumpTrace -- TraceBuffer: dumps >

' TODO
' TraceBuffer (size, circular)
' TraceSession (mode-(async-(action-(start,dump,stop)),sync),ignore_signals,duration,initial_sleep)

@enduml